// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnSkIRy53ZCPchoEsZQB9Ahq2ZSuXF7CI',
    appId: '1:321213425353:web:a5350619e5018217d9cf18',
    messagingSenderId: '321213425353',
    projectId: 'chat-app-b17fb',
    authDomain: 'chat-app-b17fb.firebaseapp.com',
    storageBucket: 'chat-app-b17fb.firebasestorage.app',
    measurementId: 'G-T3HDRH1YBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzUWPYskxyPfQ3_LgDFSl_lhjgqahZGFE',
    appId: '1:321213425353:android:5e77a88f961ba957d9cf18',
    messagingSenderId: '321213425353',
    projectId: 'chat-app-b17fb',
    storageBucket: 'chat-app-b17fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALYcYCYScOTzNU1bntmjYZNdRCSowYEqU',
    appId: '1:321213425353:ios:cd960e997732fcb1d9cf18',
    messagingSenderId: '321213425353',
    projectId: 'chat-app-b17fb',
    storageBucket: 'chat-app-b17fb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALYcYCYScOTzNU1bntmjYZNdRCSowYEqU',
    appId: '1:321213425353:ios:cd960e997732fcb1d9cf18',
    messagingSenderId: '321213425353',
    projectId: 'chat-app-b17fb',
    storageBucket: 'chat-app-b17fb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnSkIRy53ZCPchoEsZQB9Ahq2ZSuXF7CI',
    appId: '1:321213425353:web:d75aea0018bce88ed9cf18',
    messagingSenderId: '321213425353',
    projectId: 'chat-app-b17fb',
    authDomain: 'chat-app-b17fb.firebaseapp.com',
    storageBucket: 'chat-app-b17fb.firebasestorage.app',
    measurementId: 'G-G1TKMRRVL5',
  );
}
